Repository openshift/csi-operator, pull requests merged in 2018-12, with the labels that each got.

#37 Add EBS sample deployment file
  deploy/ebs.yaml
Labels: approved, lgtm, size/M

#38 Use correct context timeouts
  pkg/controller/csidriverdeployment/csidriverdeployment_controller.go
  test/e2e/e2e_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#39 Move EBS deployment sample to the right place
  deploy/samples/ebs.yaml
Labels: approved, lgtm, size/XS
