Repository openshift/csi-operator, pull requests merged in 2023-12, with the labels that each got.

#79 OCPBUGS-23306: Add annotation to CSI driver Pod preventing eviction from the cluster-autoscaler
  assets/base/node.yaml
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#85 STOR-1688: Chore: add .snyk file to ignore false positives
  .snyk
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#80 NO-JIRA: Add "Quick start" section to `README.md`
  README.md
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#84 OCPBUGS-25125: Create RBAC objects first
  pkg/generated-assets/generated_assets.go
  pkg/generated-assets/sanitize.go
  pkg/generator/asset_generator.go
Labels: lgtm, approved, docs-approved, px-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#89 OCPBUGS-24245: Add selinux
  assets/overlays/aws-ebs/base/csidriver.yaml
  assets/overlays/aws-ebs/generated/hypershift/csidriver.yaml
  assets/overlays/aws-ebs/generated/standalone/csidriver.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
