Repository openshift/csi-operator, pull requests merged in 2024-04, with the labels that each got.

#205 STOR-1726: Minimal implementation of CIFS/Samba CSI driver operator
  assets/overlays/samba/generated/standalone/configmap_and_secret_reader_provisioner_binding.yaml
  assets/overlays/samba/generated/standalone/controller.yaml
  assets/overlays/samba/generated/standalone/controller_pdb.yaml
  assets/overlays/samba/generated/standalone/controller_privileged_binding.yaml
  assets/overlays/samba/generated/standalone/controller_sa.yaml
  assets/overlays/samba/generated/standalone/csidriver.yaml
  assets/overlays/samba/generated/standalone/lease_leader_election_binding.yaml
  assets/overlays/samba/generated/standalone/lease_leader_election_role.yaml
  assets/overlays/samba/generated/standalone/main_provisioner_binding.yaml
  assets/overlays/samba/generated/standalone/manifests.yaml
  assets/overlays/samba/generated/standalone/node.yaml
  assets/overlays/samba/generated/standalone/node_privileged_binding.yaml
  assets/overlays/samba/generated/standalone/node_sa.yaml
  assets/overlays/samba/generated/standalone/privileged_role.yaml
  cmd/smb-csi-driver-operator/main.go
  pkg/driver/samba/samba.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#209 STOR-1726: Add Dockerfile for Samba operator
  Dockerfile.samba
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#211 STOR-1726: Simple rename of objects in `assets/overlays/samba/generated/standalone/`
  assets/overlays/samba/generated/standalone/node.yaml
  assets/overlays/samba/generated/standalone/node_privileged_binding.yaml
  assets/overlays/samba/generated/standalone/node_sa.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#204 STOR-1818: enable pvcDataSource capability for tests
  test/e2e/azure-file/manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#212 STOR-1726: Add test manifest for SMB CSI driver
  test/e2e/samba/manifest.yaml
  test/e2e/samba/samba-server.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#210 STOR-1726: Add OLM metadata for SMB operator
  config/samba/bundle.Dockerfile
  config/samba/manifests/art.yaml
  config/samba/manifests/preview/image-references
  config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/smb-csi-driver-operator.package.yaml
  config/samba/metadata/annotations.yaml
  hack/.gitignore
  hack/create-samba-bundle
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#214 OCPBUGS-28230: enforce termination message policy on all platform pods
  assets/common/sidecars/attacher.yaml
  assets/common/sidecars/driver_kube_rbac_proxy.yaml
  assets/common/sidecars/node_driver_registrar.yaml
  assets/common/sidecars/provisioner.yaml
  assets/common/sidecars/resizer.yaml
  assets/common/sidecars/snapshotter.yaml
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
  assets/overlays/aws-ebs/patches/controller_add_driver.yaml
  assets/overlays/aws-ebs/patches/controller_add_hypershift_controller_minter.yaml
  assets/overlays/aws-ebs/patches/node_add_driver.yaml
  assets/overlays/azure-disk/generated/hypershift/controller.yaml
  assets/overlays/azure-disk/generated/hypershift/node.yaml
  assets/overlays/azure-disk/generated/standalone/controller.yaml
  assets/overlays/azure-disk/generated/standalone/node.yaml
  assets/overlays/azure-disk/patches/controller_add_driver.yaml
  assets/overlays/azure-disk/patches/controller_add_standalone_injector.yaml
  assets/overlays/azure-disk/patches/node_add_driver.yaml
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/generated/hypershift/node.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/generated/standalone/node.yaml
  assets/overlays/azure-file/patches/controller_add_driver.yaml
  assets/overlays/azure-file/patches/controller_add_standalone_injector.yaml
  assets/overlays/azure-file/patches/node_add_driver.yaml
Labels: lgtm, approved, docs-approved, px-approved, jira/valid-bug, jira/valid-reference

#206 OCPBUGS-31306: Azure Disk: Add cluster-wide proxy in the driver container in the node
  pkg/driver/azure-disk/azure_disk.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#207 OCPBUGS-31044: Add cluster-wide proxy in the azure-file driver node container
  pkg/driver/azure-file/azure_file.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#213 NO-JIRA: Remove unused assests for __azure-file__
  assets/overlays/azure-file/generated/hypershift/main_snapshotter_binding.yaml
  assets/overlays/azure-file/generated/standalone/main_snapshotter_binding.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#170 AUTH-482: set required-scc for openshift workloads
  assets/base/node.yaml
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
  assets/overlays/aws-ebs/patches/controller_add_driver.yaml
  assets/overlays/azure-disk/generated/hypershift/node.yaml
  assets/overlays/azure-disk/generated/standalone/node.yaml
  assets/overlays/azure-file/generated/hypershift/node.yaml
  assets/overlays/azure-file/generated/standalone/node.yaml
  pkg/driver/common/operator/test_manifests/aws_ebs_controller_hypershift.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#215 STOR-1726: Delete static resources when ClusterCSIDriver is removed
  pkg/driver/aws-ebs/aws_ebs.go
  pkg/driver/azure-disk/azure_disk.go
  pkg/driver/azure-file/azure_file.go
  pkg/driver/samba/samba.go
  pkg/operator/config/config.go
  pkg/operator/starter.go
  pkg/operator/starter_test.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#216 OCPBUGS-28230: Add terminationMessagePolicy to all containers
  assets/common/sidecars/livenessprobe.yaml
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
  assets/overlays/azure-disk/generated/hypershift/controller.yaml
  assets/overlays/azure-disk/generated/hypershift/node.yaml
  assets/overlays/azure-disk/generated/standalone/controller.yaml
  assets/overlays/azure-disk/generated/standalone/node.yaml
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/generated/hypershift/node.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/generated/standalone/node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
