Repository openshift/csi-operator, pull requests merged in 2024-09, with the labels that each got.

#274 [release-4.17] OCPBUGS-38355: Bump openshift/api to get EFS volume metrics
  go.mod
  go.sum
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#273 STOR-1422: Bump(openshift/api): to get EFS volume metrics GA
  go.mod
  go.sum
  vendor/github.com/openshift/api/.ci-operator.yaml
  vendor/github.com/openshift/api/Dockerfile.ocp
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/envtest-releases.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#282 OCPBUGS-41265: Disable LUN stress test for azure-disk
  test/e2e/azure-disk/ocp-manifest.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#279 NO-JIRA: Move doc on migrating CSI Driver in-tree
  README.md
  doc/migrating-operators.md
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#277 NO-JIRA: List all supported operators in README
  Makefile
  README.md
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference
