Repository openshift/csi-operator, pull requests merged in 2024-08, with the labels that each got.

#251 STOR-1856: add STS hook for EFS credentials request controller
  doc/aws-efs/README.md
  pkg/driver/aws-efs/aws_efs.go
  pkg/driver/aws-efs/aws_efs_test.go
  pkg/generated-assets/generated_assets.go
  pkg/operator/config/config.go
  pkg/operator/starter.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#248 OCPBUGS-37488: add init container in EBS CSI controller pod
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/patches/controller_add_driver.yaml
  go.mod
  go.sum
  pkg/driver/aws-ebs/aws_ebs_test.go
  pkg/driver/common/operator/replacer.go
  pkg/driver/common/operator/test_manifests/aws_ebs_controller_hypershift.yaml
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#253 STOR-2002: add Azure File snapshot support
  assets/overlays/azure-file/base/volumesnapshotclass.yaml
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/generated/hypershift/main_snapshotter_binding.yaml
  assets/overlays/azure-file/generated/hypershift/manifests.yaml
  assets/overlays/azure-file/generated/hypershift/service.yaml
  assets/overlays/azure-file/generated/hypershift/volumesnapshot_reader_provisioner_binding.yaml
  assets/overlays/azure-file/generated/hypershift/volumesnapshotclass.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/generated/standalone/main_snapshotter_binding.yaml
  assets/overlays/azure-file/generated/standalone/manifests.yaml
  assets/overlays/azure-file/generated/standalone/service.yaml
  assets/overlays/azure-file/generated/standalone/servicemonitor.yaml
  assets/overlays/azure-file/generated/standalone/volumesnapshot_reader_provisioner_binding.yaml
  assets/overlays/azure-file/generated/standalone/volumesnapshotclass.yaml
  pkg/driver/azure-file/azure_file.go
  test/e2e/azure-file/manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#250 NO-JIRA: use service account namespace placeholder for smb role bindings
  assets/overlays/samba/generated/standalone/configmap_and_secret_reader_provisioner_binding.yaml
  assets/overlays/samba/generated/standalone/controller_privileged_binding.yaml
  assets/overlays/samba/generated/standalone/lease_leader_election_binding.yaml
  assets/overlays/samba/generated/standalone/main_provisioner_binding.yaml
  assets/overlays/samba/generated/standalone/node_privileged_binding.yaml
  assets/overlays/samba/patches/binding_with_namespace_placeholder_controller.yaml
  assets/overlays/samba/patches/binding_with_namespace_placeholder_node.yaml
  pkg/driver/samba/samba.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#254 STOR-1819: Add manifest with OCP specific test config
  test/e2e/aws-ebs/ocp-manifest.yaml
  test/e2e/azure-disk/ocp-manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#255 STOR-1422: Volume Metrics for EFS CSI Driver
  go.mod
  go.sum
  pkg/driver/aws-efs/aws_efs.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/modules.txt
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#258 STOR-1819: Add manifest with OCP specific test config
  test/e2e/aws-efs/ocp-manifest.yaml
  test/e2e/azure-file/ocp-manifest.yaml
  test/e2e/samba/ocp-manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#252 STOR-1993: add init container in EFS CSI controller pod
  assets/overlays/aws-efs/generated/standalone/controller.yaml
  assets/overlays/aws-efs/patches/controller_add_driver.yaml
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/aws-efs/manifests/stable/image-references
  doc/aws-efs/README.md
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#261 OCPBUGS-38578: efs: fix tools image reference
  config/aws-efs/manifests/stable/image-references
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#259 STOR-2009: Bump OLM metadata to 4.18
  config/aws-efs/manifests/aws-efs-csi-driver-operator.package.yaml
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/smb-csi-driver-operator.package.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#262 OCPBUGS-38620: Some CSI driver containers missing terminationMessagePolicy
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/patches/controller_add_driver.yaml
  assets/overlays/aws-efs/generated/standalone/controller.yaml
  assets/overlays/aws-efs/generated/standalone/node.yaml
  assets/overlays/aws-efs/patches/controller_add_driver.yaml
  assets/overlays/aws-efs/patches/node_add_driver.yaml
  assets/overlays/samba/generated/standalone/controller.yaml
  assets/overlays/samba/generated/standalone/node.yaml
  assets/overlays/samba/patches/controller_add_driver.yaml
  assets/overlays/samba/patches/node_add_driver.yaml
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#260 STOR-1819: Distribute OCP specific test manifest with create-efs-volume
  Dockerfile.create_efs
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#264 OCPBUGS-38578: Update aws-efs-csi-driver-operator image-references name
  config/aws-efs/manifests/stable/image-references
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-bug, jira/valid-reference

#265 OCPBUGS-38815: add init container in EFS CSI controller pod
  assets/overlays/aws-efs/generated/standalone/controller.yaml
  assets/overlays/aws-efs/patches/controller_add_driver.yaml
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/aws-efs/manifests/stable/image-references
  doc/aws-efs/README.md
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#263 [4.17] OCPBUGS-38736: Some CSI driver containers missing terminationMessagePolicy
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/patches/controller_add_driver.yaml
  assets/overlays/aws-efs/generated/standalone/node.yaml
  assets/overlays/aws-efs/patches/node_add_driver.yaml
  assets/overlays/samba/generated/standalone/controller.yaml
  assets/overlays/samba/generated/standalone/node.yaml
  assets/overlays/samba/patches/controller_add_driver.yaml
  assets/overlays/samba/patches/node_add_driver.yaml
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
