Repository openshift/csi-operator, pull requests merged in 2024-03, with the labels that each got.

#187 STOR-1464: Enable RWOP tests in CI
  legacy/aws-ebs-csi-driver-operator/test/e2e/manifest.yaml
  legacy/azure-disk-csi-driver-operator/test/e2e/manifest.yaml
  legacy/azure-file-csi-driver-operator/test/e2e/manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#194 OCPBUGS-30620: move test manifests to top-level directory
  Makefile
  test/e2e/aws-ebs/manifest.yaml
  test/e2e/azure-disk/manifest.yaml
  test/e2e/azure-file/manifest.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#174 NO-JIRA: Configure dependabot for security updates only
  .github/dependabot.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#199 OCPBUGS-23260: Explicitly reserve 1 attachment for the root disk
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
  assets/overlays/aws-ebs/patches/node_add_driver.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#200 STOR-1794: add location for azcopy logs
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/patches/controller_add_driver.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#195 [4.15] OCPBUGS-30621: move test manifest to top-level directory
  Dockerfile.test
  Makefile
  test/e2e/aws-ebs/manifest.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
