Repository openshift/csi-operator, pull requests merged in 2024-07, with the labels that each got.

#202 STOR-1290: don't pass credentials via environment variables in AWS EBS
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/patches/controller_add_driver.yaml
  pkg/driver/aws-ebs/aws_ebs_test.go
  pkg/driver/common/operator/test_manifests/aws_ebs_controller_hypershift.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#238 OCPBUGS-34451: Bump go version to be consistent with ART
  .ci-operator.yaml
  Dockerfile.aws-ebs
  Dockerfile.aws-efs
  Dockerfile.azure-disk
  Dockerfile.azure-file
  Dockerfile.create_efs
  Dockerfile.samba
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#249 OCPBUGS-37274: Add FIPS_ENABLED to env vars for aws-efs-csi-driver (2)
  pkg/driver/aws-efs/aws_efs.go
  pkg/driver/aws-efs/aws_efs_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference
