Repository openshift/csi-operator, pull requests merged in 2024-11, with the labels that each got.

#299 NO-JIRA: Add OWNERS files for OpenStack-specific components/assets
  assets/overlays/openstack-cinder/OWNERS
  cmd/openstack-cinder-csi-driver-operator/OWNERS
  pkg/driver/openstack-cinder/OWNERS
  pkg/openstack-cinder/OWNERS
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#288 OSASINFRA-3620: Add manila csi
  Dockerfile.openstack-manila
  assets/overlays/openstack-manila/base/csidriver.yaml
  assets/overlays/openstack-manila/base/node_nfs.yaml
  assets/overlays/openstack-manila/base/volumesnapshotclass.yaml
  assets/overlays/openstack-manila/generated/standalone/cabundle_cm.yaml
  assets/overlays/openstack-manila/generated/standalone/controller.yaml
  assets/overlays/openstack-manila/generated/standalone/controller_pdb.yaml
  assets/overlays/openstack-manila/generated/standalone/controller_sa.yaml
  assets/overlays/openstack-manila/generated/standalone/csidriver.yaml
  assets/overlays/openstack-manila/generated/standalone/kube_rbac_proxy_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/kube_rbac_proxy_role.yaml
  assets/overlays/openstack-manila/generated/standalone/lease_leader_election_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/lease_leader_election_role.yaml
  assets/overlays/openstack-manila/generated/standalone/main_provisioner_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/main_resizer_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/main_snapshotter_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/manifests.yaml
  assets/overlays/openstack-manila/generated/standalone/node.yaml
  assets/overlays/openstack-manila/generated/standalone/node_nfs.yaml
  assets/overlays/openstack-manila/generated/standalone/node_privileged_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/node_sa.yaml
  assets/overlays/openstack-manila/generated/standalone/privileged_role.yaml
  assets/overlays/openstack-manila/generated/standalone/prometheus_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/prometheus_role.yaml
  assets/overlays/openstack-manila/generated/standalone/service.yaml
  assets/overlays/openstack-manila/generated/standalone/servicemonitor.yaml
  assets/overlays/openstack-manila/generated/standalone/storageclass_reader_resizer_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/volumesnapshot_reader_provisioner_binding.yaml
  assets/overlays/openstack-manila/generated/standalone/volumesnapshotclass.yaml
  assets/overlays/openstack-manila/patches/controller_add_driver.yaml
  assets/overlays/openstack-manila/patches/node_add_driver.yaml
  cmd/generator/main.go
  cmd/openstack-manila-csi-driver-operator/main.go
  go.mod
  go.sum
  pkg/clients/builder.go
  pkg/clients/clients.go
  pkg/driver/common/generator/port_registry.go
  pkg/driver/common/operator/replacer.go
  pkg/driver/openstack-manila/openstack_manila.go
  pkg/openstack-manila/client/openstack.go
  pkg/openstack-manila/secret/secretsync.go
  pkg/openstack-manila/util/const.go
  pkg/operator/config/config.go
  pkg/operator/starter.go
  pkg/operator/starter_controller.go
  pkg/operator/starter_test.go
  vendor/github.com/gophercloud/gophercloud/v2/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/v2/openstack/sharedfilesystems/v2/sharetypes/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/sharedfilesystems/v2/sharetypes/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/sharedfilesystems/v2/sharetypes/urls.go
  vendor/github.com/gophercloud/gophercloud/v2/provider_client.go
  vendor/modules.txt
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#316 OSASINFRA-3654: Include OpenStack test manifest to test/e2e
  test/e2e/openstack-cinder/manifest.yaml
  test/e2e/openstack-manila/manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#315 NO-JIRA: Add openstack-approvers to root OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#312 OSASINFRA-3638: Add support for Hypershift to Manila CSI
  assets/overlays/openstack-manila/generated/hypershift/cabundle_cm.yaml
  assets/overlays/openstack-manila/generated/hypershift/controller.yaml
  assets/overlays/openstack-manila/generated/hypershift/controller_pdb.yaml
  assets/overlays/openstack-manila/generated/hypershift/controller_sa.yaml
  assets/overlays/openstack-manila/generated/hypershift/csidriver.yaml
  assets/overlays/openstack-manila/generated/hypershift/lease_leader_election_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/lease_leader_election_role.yaml
  assets/overlays/openstack-manila/generated/hypershift/main_provisioner_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/main_resizer_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/main_snapshotter_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/manifests.yaml
  assets/overlays/openstack-manila/generated/hypershift/node.yaml
  assets/overlays/openstack-manila/generated/hypershift/node_nfs.yaml
  assets/overlays/openstack-manila/generated/hypershift/node_privileged_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/node_sa.yaml
  assets/overlays/openstack-manila/generated/hypershift/privileged_role.yaml
  assets/overlays/openstack-manila/generated/hypershift/service.yaml
  assets/overlays/openstack-manila/generated/hypershift/storageclass_reader_resizer_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/volumesnapshot_reader_provisioner_binding.yaml
  assets/overlays/openstack-manila/generated/hypershift/volumesnapshotclass.yaml
  assets/overlays/openstack-manila/patches/controller_add_hypershift_volumes.yaml
  assets/overlays/openstack-manila/patches/controller_rename_config_map.yaml
  pkg/driver/openstack-manila/openstack_manila.go
  pkg/openstack-manila/secret/secretsync.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#318 OCPBUGS-44340: Fix error handling for starter controller
  pkg/driver/openstack-manila/openstack_manila.go
  pkg/operator/starter_controller.go
  pkg/operator/starter_controller_test.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#321 OSASINFRA-3535: openstack-cinder: Watch management cluster for cloud-provider config
  pkg/openstack-cinder/config/configsync.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#295 NO-JIRA: ignore cmd/generator/main.go in .snyk
  .snyk
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#306 AUTH-482: set required-scc for openshift workloads
  assets/overlays/aws-efs/generated/standalone/controller.yaml
  assets/overlays/aws-efs/patches/controller_add_driver.yaml
  assets/overlays/azure-disk/generated/hypershift/controller.yaml
  assets/overlays/azure-disk/generated/standalone/controller.yaml
  assets/overlays/azure-disk/patches/controller_add_driver.yaml
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/patches/controller_add_driver.yaml
  assets/overlays/samba/generated/standalone/controller.yaml
  assets/overlays/samba/patches/controller_add_driver.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#322 OSASINFRA-3626: Resize support with the OpenStack Manila CSI Driver
  README.md
  assets/overlays/openstack-manila/generated/hypershift/controller.yaml
  assets/overlays/openstack-manila/generated/standalone/controller.yaml
  pkg/driver/openstack-manila/openstack_manila.go
  test/e2e/openstack-manila/manifest.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#326 OCPBUGS-43357: support hcp tolerations
  pkg/driver/common/operator/hooks.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
