Repository openshift/csi-operator, pull requests merged in 2024-10, with the labels that each got.

#287 NO-JIRA: Remove generated assets before generation
  assets/overlays/azure-disk/generated/hypershift/storageclass_ash.yaml
  assets/overlays/azure-disk/generated/hypershift/volumesnapshotclass_ash.yaml
  assets/overlays/azure-disk/generated/standalone/storageclass_ash.yaml
  assets/overlays/azure-disk/generated/standalone/volumesnapshotclass_ash.yaml
  cmd/generator/main.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#285 NO-JIRA: Add SidecarConfig.WithPatches
  pkg/generator/types.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#289 OCPBUGS-41365: add ability to control kube rbac proxy container image…
  pkg/driver/common/operator/hooks.go
  pkg/driver/common/operator/hooks_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#272 OCPBUGS-38922: add tag matching to Azure File storage class
  assets/overlays/azure-file/base/storageclass.yaml
  assets/overlays/azure-file/generated/hypershift/storageclass.yaml
  assets/overlays/azure-file/generated/standalone/storageclass.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#293 OCPBUGS-42939: Correct aws efs csi driver config as removable
  pkg/driver/aws-efs/aws_efs.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#300 STOR-1844: update OLM manifests to use stable channel
  config/samba/bundle.Dockerfile
  config/samba/manifests/art.yaml
  config/samba/manifests/preview
  config/samba/manifests/smb-csi-driver-operator.package.yaml
  config/samba/manifests/stable/image-references
  config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
  config/samba/metadata/annotations.yaml
  hack/create-samba-bundle
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#307 OCPBUGS-43653: Add missing credentials secret hook
  pkg/driver/openstack-cinder/openstack_cinder.go
  pkg/operator/config/config.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#304 OCPBUGS-43562: Add missing proxy hook for `openstack-cinder` driver
  pkg/driver/openstack-cinder/openstack_cinder.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#290 OCPBUGS-42325: Set separate secrets for file and disk config on HyperShift
  assets/overlays/azure-disk/generated/hypershift/controller.yaml
  assets/overlays/azure-disk/patches/controller_add_hypershift_controller.yaml
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/patches/controller_add_hypershift_controller.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-bug, jira/valid-reference

#309 HOSTEDCP-2032: Set azure disk & file Secrets Store CSI Volume
  go.mod
  pkg/driver/azure-disk/azure_disk.go
  pkg/driver/azure-file/azure_file.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference
