Repository openshift/csi-operator, pull requests merged in 2025-03, with the labels that each got.

#297 CFE-1131: AWS Tags DAY2 Update
  pkg/driver/aws-ebs/aws_ebs.go
  pkg/driver/aws-ebs/aws_ebs_tags_controller.go
  pkg/driver/aws-ebs/aws_ebs_tags_controller_test.go
  pkg/driver/aws-ebs/aws_ebs_tags_queue_worker.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#313 CFE-1132: EFS Access Point Tags Update DAY2
  pkg/driver/aws-efs/aws_efs.go
  pkg/driver/aws-efs/aws_efs_tags_controller.go
  pkg/driver/aws-efs/aws_efs_tags_controller_test.go
  pkg/driver/aws-efs/aws_efs_tags_queue_worker.go
  pkg/driver/aws-efs/aws_efs_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#363 NO-JIRA: NO-JIRA: Remove bertinatto from OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, qe-approved, jira/valid-reference

#348 NO-JIRA: Fixed typo in README.md
  README.md
Labels: lgtm, approved, ok-to-test, qe-approved, jira/valid-reference

#357 OCPBUGS-41827: update injector to use a secret rather than an environment variable
  assets/overlays/azure-disk/generated/hypershift/node.yaml
  assets/overlays/azure-disk/generated/standalone/controller.yaml
  assets/overlays/azure-disk/generated/standalone/node.yaml
  assets/overlays/azure-disk/patches/controller_add_standalone_injector.yaml
  assets/overlays/azure-disk/patches/node_add_driver.yaml
  assets/overlays/azure-file/generated/hypershift/node.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/generated/standalone/node.yaml
  assets/overlays/azure-file/patches/controller_add_standalone_injector.yaml
  assets/overlays/azure-file/patches/node_add_driver.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#367 STOR-1880: Role and ClusterRole with too wide permissions
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#368 STOR-1877: Run operators without root user control
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#372 OCPBUGS-54230: Bump library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#371 OCPBUGS-54180: Disable remove-not-ready-taint for azure disk csi driver
  assets/overlays/azure-disk/generated/hypershift/node.yaml
  assets/overlays/azure-disk/generated/standalone/node.yaml
  assets/overlays/azure-disk/patches/node_add_driver.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
