Repository openshift/csi-operator, pull requests merged in 2025-02, with the labels that each got.

#308 NO-JIRA: Remove `inject-proxy` annotations for aws-ebs, aws-efs node daemonsets
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
  assets/overlays/aws-ebs/patches/node_add_driver.yaml
  assets/overlays/aws-efs/generated/standalone/node.yaml
  assets/overlays/aws-efs/patches/node_add_driver.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#358 STOR-2263: Enable csi resize and inline volume support for smb csi driver
  assets/overlays/samba/base/csi-driver-cluster-role-binding.yaml
  assets/overlays/samba/base/csi-driver-cluster-role.yaml
  assets/overlays/samba/base/csidriver.yaml
  assets/overlays/samba/generated/standalone/controller.yaml
  assets/overlays/samba/generated/standalone/csi-driver-cluster-role-binding.yaml
  assets/overlays/samba/generated/standalone/csi-driver-cluster-role.yaml
  assets/overlays/samba/generated/standalone/csidriver.yaml
  assets/overlays/samba/generated/standalone/main_resizer_binding.yaml
  assets/overlays/samba/generated/standalone/manifests.yaml
  assets/overlays/samba/generated/standalone/service.yaml
  assets/overlays/samba/generated/standalone/servicemonitor.yaml
  assets/overlays/samba/generated/standalone/storageclass_reader_resizer_binding.yaml
  config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
  pkg/driver/samba/samba.go
  test/e2e/samba/manifest.yaml
  test/e2e/samba/samba-server.yaml
Labels: lgtm, approved, tide/merge-method-squash, qe-approved, jira/valid-reference

#360 STOR-2263: correct smb csi driver test manifest
  test/e2e/samba/manifest.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference
