Repository openshift/csi-operator, pull requests merged in 2025-04, with the labels that each got.

#369 OCPBUGS-54447: Enable required driver services
  assets/overlays/openstack-manila/generated/hypershift/controller.yaml
  assets/overlays/openstack-manila/generated/hypershift/node.yaml
  assets/overlays/openstack-manila/generated/standalone/controller.yaml
  assets/overlays/openstack-manila/generated/standalone/node.yaml
  assets/overlays/openstack-manila/patches/controller_add_driver.yaml
  assets/overlays/openstack-manila/patches/node_add_driver.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#370 STOR-2126: Enable readOnlyFileSystem
  config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#345 OSASINFRA-3652: openstack-cinder: Use new --with-topology flag
  assets/overlays/openstack-cinder/generated/hypershift/controller.yaml
  assets/overlays/openstack-cinder/generated/standalone/controller.yaml
  assets/overlays/openstack-cinder/patches/controller_add_driver.yaml
  assets/overlays/openstack-cinder/patches/provisioner_add_envvars.yaml
  pkg/driver/openstack-cinder/openstack_cinder.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#376 OCPBUGS-54382: Correct ASH driver inject env config
  pkg/driver/azure-disk/azure_disk.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#329 NO-JIRA: build only needed cmd in container image
  Dockerfile.aws-ebs
  Dockerfile.aws-efs
  Dockerfile.azure-disk
  Dockerfile.azure-file
  Dockerfile.create_efs
  Dockerfile.openstack-cinder
  Dockerfile.openstack-manila
  Dockerfile.samba
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#364 OCPBUGS-50493: Use 127.0.0.1 for healtz http-endpoints
  assets/common/sidecars/host_network_livenessprobe.yaml
  assets/common/sidecars/node_driver_registrar.yaml
  assets/common/sidecars/pod_network_livenessprobe.yaml
  assets/overlays/aws-ebs/generated/hypershift/controller.yaml
  assets/overlays/aws-ebs/generated/hypershift/node.yaml
  assets/overlays/aws-ebs/generated/standalone/controller.yaml
  assets/overlays/aws-ebs/generated/standalone/node.yaml
  assets/overlays/aws-ebs/patches/node_add_driver.yaml
  assets/overlays/aws-efs/generated/standalone/controller.yaml
  assets/overlays/aws-efs/generated/standalone/node.yaml
  assets/overlays/aws-efs/patches/node_add_driver.yaml
  assets/overlays/azure-disk/generated/hypershift/controller.yaml
  assets/overlays/azure-disk/generated/hypershift/node.yaml
  assets/overlays/azure-disk/generated/standalone/controller.yaml
  assets/overlays/azure-disk/generated/standalone/node.yaml
  assets/overlays/azure-disk/patches/node_add_driver.yaml
  assets/overlays/azure-file/generated/hypershift/controller.yaml
  assets/overlays/azure-file/generated/hypershift/node.yaml
  assets/overlays/azure-file/generated/standalone/controller.yaml
  assets/overlays/azure-file/generated/standalone/node.yaml
  assets/overlays/azure-file/patches/node_add_driver.yaml
  assets/overlays/openstack-cinder/generated/hypershift/controller.yaml
  assets/overlays/openstack-cinder/generated/hypershift/node.yaml
  assets/overlays/openstack-cinder/generated/standalone/controller.yaml
  assets/overlays/openstack-cinder/generated/standalone/node.yaml
  assets/overlays/openstack-cinder/patches/node_add_driver.yaml
  assets/overlays/openstack-manila/generated/hypershift/controller.yaml
  assets/overlays/openstack-manila/generated/hypershift/node.yaml
  assets/overlays/openstack-manila/generated/standalone/controller.yaml
  assets/overlays/openstack-manila/generated/standalone/node.yaml
  assets/overlays/openstack-manila/patches/node_add_driver.yaml
  assets/overlays/samba/generated/standalone/controller.yaml
  assets/overlays/samba/generated/standalone/node.yaml
  assets/overlays/samba/patches/node_add_driver.yaml
  pkg/driver/aws-ebs/aws_ebs.go
  pkg/driver/aws-efs/aws_efs.go
  pkg/driver/azure-disk/azure_disk.go
  pkg/driver/azure-file/azure_file.go
  pkg/driver/common/generator/base_assets.go
  pkg/driver/openstack-cinder/openstack_cinder.go
  pkg/driver/openstack-manila/openstack_manila.go
  pkg/driver/samba/samba.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
