Repository openshift/csi-operator, pull requests merged in 2025-01, with the labels that each got.

#352 NO-JIRA: Update golang.org/x/net to v0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#314 STOR-2078: Enable VolumeAttributesClass on AWS EBS for resizer + provisioner
  assets/base/rbac/volumeattributesclass_reader_provisioner_binding.yaml
  assets/base/rbac/volumeattributesclass_reader_resizer_binding.yaml
  assets/overlays/aws-ebs/generated/hypershift/manifests.yaml
  assets/overlays/aws-ebs/generated/hypershift/volumeattributesclass_reader_provisioner_binding.yaml
  assets/overlays/aws-ebs/generated/hypershift/volumeattributesclass_reader_resizer_binding.yaml
  assets/overlays/aws-ebs/generated/standalone/manifests.yaml
  assets/overlays/aws-ebs/generated/standalone/volumeattributesclass_reader_provisioner_binding.yaml
  assets/overlays/aws-ebs/generated/standalone/volumeattributesclass_reader_resizer_binding.yaml
  pkg/driver/aws-ebs/aws_ebs.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#353 OCPBUGS-48507: openstack-manila: update PodDisruptionBudget name
  assets/overlays/openstack-manila/generated/hypershift/controller_pdb.yaml
  assets/overlays/openstack-manila/generated/standalone/controller_pdb.yaml
  assets/overlays/openstack-manila/patches/modify_pdb.yaml
  pkg/driver/openstack-manila/openstack_manila.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only
